### ISSUE TITLE
deleteBy endpoint should only accept a subset of searchParams

### ISSUE THREAD

**Issue by clemfromspace** [algolia/api-clients-automation#1015]
## Describe the problem

`deleteBy` endpoint should only accept a subset of `searchParams`, cf: https://www.algolia.com/doc/rest-api/search/#delete-by
> This endpoint doesn’t support all the options of a query, only its filters (numeric, facet, or tag) and geo queries. It also doesn’t accept empty filters or query.

## Describe the solution

Create a subset of the `searchParam` (but it would involve quite a lot of changes I guess?)

**Comment by shortcuts** [comment]
Thanks for the issue, good catch!

Most of the filters should already be defined in the [`searchParams.yml` file](https://github.com/algolia/api-clients-automation/blob/main/specs/common/schemas/SearchParams.yml) outside of the `SearchParams` object. We can do the same for the ones that are allowed by `deleteBy`.

Once the above is done, we can create a new `deleteByParams` object which only takes reference to those filters:

```yml
deleteByParams:
  type: object
  additionalProperties: false
  properties:
    facetFilters:
      $ref: '#/facetFilters'
  // ... the other params
```

And use it in the method
