### ISSUE TITLE
Documentation error in Java documentation to send data to Algolia

### ISSUE THREAD

**Issue by FDelporte** [algolia/api-clients-automation#1163]
## Description

BatchOperation needs to be replaced with BatchRequest

## Expected behavior

This page
https://api-clients-automation.netlify.app/docs/clients/guides/send-data-to-algolia

## Environment

- Java API

**Comment by shortcuts** [comment]
Hey! Great find thanks :)

**Comment by shortcuts** [comment]
(This have been fixed)
