### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module ...client-search.cjs.js

### ISSUE THREAD

**Issue by loick** [algolia/api-clients-automation#1893]
Version used: 
```js
{
  "@algolia/client-search": "5.0.0-alpha.73",
  "@algolia/recommend": "5.0.0-alpha.73",
}
```
Hi everyone, 

I'm currently using your new alpha version and I've been suddenly blocked when trying to upgrade the v73: 
```sh
Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/@algolia/client-search/dist/client-search.cjs.js from /vercel/path0/{path} not supported.
```

My configuration didn't change, I'm using typescript, and I'm importing the library this way: 

```js
const { searchClient } = await import('@algolia/client-search')
```

any idea? 

Thanks!

**Comment by shortcuts** [comment]
hey @loick thanks for reporting the issue!

most likely similar to https://github.com/algolia/api-clients-automation/issues/1884, we introduced ESM to the clients in .73, I'll try to work on a fix today!

**Comment by shortcuts** [comment]
coming back to this, our exported files and `package.json`s seems correct, would you have the time to provide a way to reproduce the issue? or is your repo open-source?

also, there's this small doc about ESMs on the next.js doc https://nextjs.org/docs/messages/import-esm-externals

**Comment by shortcuts** [comment]
hey, https://github.com/algolia/api-clients-automation/pull/1894 seems to have fixed the issue, at least I can't reproduce anymore locally! Feel free to try and let me know :D
