### ISSUE TITLE
[bug]: Usage API client uses wrong API URL

### ISSUE THREAD

**Issue by kai687** [algolia/api-clients-automation#3621]
### Description

(Tested with JavaScript `@algolia/client-usage` version 1.2.3 but also seen for Python) 
The Usage API client seems to use the Search API hosts `https://{appId}-dsn.algolia.net`, etc.

It should use `usage.algolia.com` (the Usage API spec itself is correct here).

### Language

All

### Client

Usage

### Steps to reproduce

1. Call any method on the Usage API client, or print the config/hosts that the client uses.
2. Observe that the URLs are those of the Search API and not `usage.algolia.com`.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by shortcuts** [comment]
oopsie, on it, thanks for reporting!
