### ISSUE TITLE
[bug]: v4+ Filters don't work using SearchClient::searchSingleIndex()

### ISSUE THREAD

**Issue by aykutersoy** [algolia/api-clients-automation#3698]
### Description

We're using v4.4.0 and filters don't seem to work when using `SearchClient::searchSingleIndex()`

Either I'm doing something wrong or filters in query parameters are not taken into account when searching (Please see below reproducible scenario)

I've also tried this but because `searchSingleIndex` create bodyless requestOptions below body attribute just gets overridden. 

```
...
$searchResponse = $client->searchSingleIndex(
    indexName: $indexName,
    searchParams: ['query' => ''],
    requestOptions: [
        'body' => [
            'filters' => 'value=1',
        ],
    ],
);
...
```

### Language

PHP

### Client

Search

### Steps to reproduce

```
<?php
// File: hello_algolia.php
require_once realpath(__DIR__ . "/vendor/autoload.php");

use Algolia\AlgoliaSearch\Api\SearchClient;
$appID = "ALGOLIA_APPLICATION_ID";
// API key with `addObject` and `search` ACL
$apiKey = "ALGOLIA_API_KEY";
$indexName = "test-index";

$client = SearchClient::create($appID, $apiKey);

// Create a new record
$record = [
    "objectID" => "object-1",
    "name" => "test record",
    "value" => "1",
];
$record2 = [
    "objectID" => "object-2",
    "name" => "test record 2",
    "value" => "2",
];

// Add the record to an index
$client->saveObject($indexName, $record);
$client->saveObject($indexName, $record2);

// Search for ''
$searchResponse = $client->searchSingleIndex(
    indexName: $indexName,
    searchParams: ['query' => ''],
    requestOptions: [
        'queryParameters' => [
            'filters' => 'value=1',
        ],
    ],
);

echo json_encode($searchResponse);

// Return both of the records

```

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by millotp** [comment]
Hello, this endpoints uses the read transporter to allow browser and the transporter to cache the request, can you try passing the filter like this ?
```php
$response = $client->searchSingleIndex(
    '<YOUR_INDEX_NAME>',
    ['query' => 'myQuery',
      'filters' => 'value=1',
    ],
 );
```

I will add this to the snippets if it works properly

**Comment by aykutersoy** [comment]
@millotp It worked perfectly, thank your very much for. I've also noticed the `hitsPerPage` doesn't do anything when it's in `requestOptions` but works when it's in search params

```
requestOptions: [
  'queryParameters' => [
      'hitsPerPage' => 200,
  ],
]
```

```
searchParams: [
    'query' => '',
    'filters' => 'value>1',
    'hitsPerPage' => 200,
],

```

**Comment by millotp** [comment]
Thanks for your report, I'll make the usage clearer in the next release, I know its different from the last version but this version is a breaking change and the parameters are not the same as the last client.
Sorry for the discrepancy but it will make more sense for us in the long run !
